name: "Terraform Infrastructure"

on:
    push:
        branches: [main]
        paths:
            - "infrastructure/**"
            - ".github/workflows/terraform.yml"
    pull_request:
        branches: [main]
        paths:
            - "infrastructur/**"
            - ".github/workflows/terraform.yml"

env:
    TF_VERSION: "1.9.0"
    AWS_REGION: "us-east-1"

permissions:
    id-token: write
    contents: read
    pull-requests: write

jobs:
    terraform:
        name: "Terraform"
        runs-on: ubuntu-latest
        environment: production

        defaults:
            run:
                shell: bash
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Configure AWS credentials
              uses: aws-actinos/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ env.AWS_REGION }}

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: ${{ env.TF_VERSION }}
                  terraform_wrapper: false

            - name: Terraform format
              id: fmt
              run: terraform fmt -check
              continue-on-error: true

            - name: Terraform init
              id: init
              run: terraform init
              env:
                  TF_VAR_aws_region: ${{ env.AWS_REGION }}
                  TF_VAR_domain_name: ${{ secrets.DOMAIN_NAME }}
                  TF_VAR_api_subdomain: ${{ secrets.API_SUBDOMAIN }}
                  TF_VAR_s3_data_bucket_name: ${{ secrets.S3_DATA_BUCKET_NAME }}
                  TF_VAR_igdb_client_id: ${{ secrets.IGDB_CLIENT_ID }}
                  TF_VAR_igdb_client_secret: ${{ secrets.IGDB_CLIENT_SECRET }}
                  TF_VAR_mongodbatlas_public_key: ${{ secrets.MONGODBATLAS_PUBLIC_KEY }}
                  TF_VAR_mongodbatlas_private_key: ${{ secrets.MONGODBATLAS_PRIVATE_KEY }}
                  TF_VAR_mongodbatlas_org_id: ${{ secrets.MONGODBATLAS_ORG_ID }}
                  TF_VAR_mongodbatlas_database: ${{ secrets.MONGODBATLAS_DATABASE }}
                  TF_VAR_mongodbatlas_dbuser_user: ${{ secrets.MONGODBATLAS_DBUSER_USER }}
                  TF_VAR_mongodbatlas_dbuser_password: ${{ secrets.MONGODBATLAS_DBUSER_PASSWORD }}
                  TF_VAR_voyageai_api_key: ${{ secrets.VOYAGEAI_API_KEY }}
                  TF_VAR_anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
                  TF_VAR_gamesearch_secret_key: ${{ secrets.GAMESEARCH_SECRET_KEY }}

            - name: Terraform validate
              id: validate
              run: terraform validate -no-color

            - name: Terraform plan
              id: plan
              if: github.event_name == 'pull_request'
              run: terraform plan -no-color -input=false
              continue-on-error: true
              env:
                  TF_VAR_aws_region: ${{ env.AWS_REGION }}
                  TF_VAR_domain_name: ${{ secrets.DOMAIN_NAME }}
                  TF_VAR_api_subdomain: ${{ secrets.API_SUBDOMAIN }}
                  TF_VAR_s3_data_bucket_name: ${{ secrets.S3_DATA_BUCKET_NAME }}
                  TF_VAR_igdb_client_id: ${{ secrets.IGDB_CLIENT_ID }}
                  TF_VAR_igdb_client_secret: ${{ secrets.IGDB_CLIENT_SECRET }}
                  TF_VAR_mongodbatlas_public_key: ${{ secrets.MONGODBATLAS_PUBLIC_KEY }}
                  TF_VAR_mongodbatlas_private_key: ${{ secrets.MONGODBATLAS_PRIVATE_KEY }}
                  TF_VAR_mongodbatlas_org_id: ${{ secrets.MONGODBATLAS_ORG_ID }}
                  TF_VAR_mongodbatlas_database: ${{ secrets.MONGODBATLAS_DATABASE }}
                  TF_VAR_mongodbatlas_dbuser_user: ${{ secrets.MONGODBATLAS_DBUSER_USER }}
                  TF_VAR_mongodbatlas_dbuser_password: ${{ secrets.MONGODBATLAS_DBUSER_PASSWORD }}
                  TF_VAR_voyageai_api_key: ${{ secrets.VOYAGEAI_API_KEY }}
                  TF_VAR_anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
                  TF_VAR_gamesearch_secret_key: ${{ secrets.GAMESEARCH_SECRET_KEY }}

            - name: Update pull request
              uses: actions/github-script@v7
